### PR TITLE
Wp 944 policy includes

### PR DESCRIPTION
**Pull request by steverc**
Implementation of policy file inclusion.

Jira issue: WP-944

### CODE REVIEW

**Comment by steverc** [comment]
Not sure why travis tests fails here (the second pull request is to fix tests). Notice that if I run jasmine tests they are ok...

**Comment by jplyle** [comment]
Strange.  These are Mark's tests, I believe. @slaymaker - any thoughts?

Are you running the jasmine tests through "npm test" ?

**Comment by steverc** [comment]
No, to run tests I move to test/jasmine and run 'jasmine-node policy_all.spec.js'... Is it wrong?

**Comment by steverc** [comment]
Ok, found the problem. I didn't know that npm test is running tests also in dir test/jasmine.policy.tests.working. Need to fix it...

**Comment by jplyle** [comment]
There are two sets of tests to run - if you go to the webinos-policy directory and then run "npm test" (assuming you are on Linux) you should run both.  

Ah, I've just seen your message.

**Pull request merged**
