### PR TITLE
Asynchronous prompting

### PR DESCRIPTION
**Pull request by TobyEalden**
http://jira.webinos.org/browse/WP-956

### CODE REVIEW

**Comment by habibvirji** [comment]
Apologise for pushing this. but it is breaking the build. DO you want me to merge this and fix tests in next PR?

**Comment by TobyEalden** [comment]
OK hang on, I'll fix the tests now...

**Comment by jplyle** [comment]
Travis CI seems to be having issues.  If the tests pass locally, I suggest approving the PR.

**Comment by TobyEalden** [comment]
Works for me locally:

in jasmine folder:

Finished in 67.668 seconds
37 tests, 130 assertions, 0 failures

in jasmine.tests.policy.working folder:

Finished in 13.243 seconds
25 tests, 25 assertions, 0 failures

**Pull request merged**
