### PR TITLE
WP-1080 add profile parameter to environment tag

### PR DESCRIPTION
**Pull request by ccameroni**
http://jira.webinos.org/browse/WP-1080

Added "profile" environment parameter.
I did not add new jasmine tests because at the moment validation of policies with "environment-match" tag fails. I opened a new jira issue about this http://jira.webinos.org/browse/WP-1111

### CODE REVIEW

**Comment by jplyle** [comment]
Hi Cesare,
This looks good, thanks!  Is it @smonteleone who wrote the validation code?  I think we need to include these changes as part of this pull request, to maintain some consistency, and to allow us to add tests.
John

**Comment by ccameroni** [comment]
Hi John,
I think in a few days I can resume this task to add validation changes and new tests.
I had a look at validation code and "environment-match" validation is already present. It seems to me that the validation problem is related to nested "condition" tags. In json schema, "condition" array has maxItems set to 1. I think this is good for root condition but not for nested ones. I think http://jira.webinos.org/browse/WP-1115 may be related to this problem.

**Comment by jplyle** [comment]
Ah, that might be of interest to @slaymaker 

Thanks, Cesare.  Let me know if you need anything!

**Comment by ccameroni** [comment]
As agreed I fixed validation and added new tests about environments and nested conditions.
I closed http://jira.webinos.org/browse/WP-1111 as a duplicate of this issue.

**Comment by jplyle** [comment]
This is all working for me on Linux.
Could someone test on Windows / Android?  Perhaps @andreasbotsikas and @nix4 ?

**Comment by nix4** [comment]
Test on Android passed (PZP was successfully initialized). 

NOTE: This test is limited to building android-pzp, installing webinos and running the pzp on android.

**Comment by jplyle** [comment]
Ok, we just need some confirmation that this doesn't break anything on Windows, then we're good to merge.

**Comment by ccameroni** [comment]
Please don't merge, I found a bug in condition evaluation, I'm fixing it.

**Comment by ccameroni** [comment]
Bug fixed. If everything is fine I think you can merge.

**Comment by jplyle** [comment]
I'd just like someone to test this on Windows (the npm install test is just compilation) before we merge, given the potential that the policy manager has to mess up a lot of platform.  

I take it that the default policies don't need to change at the moment, to take Environments into consideration?

**Comment by ccameroni** [comment]
I confirm, the default policies don't need to change.

**Comment by ccameroni** [comment]
I just compiled it using npm install on a win 7 virtual machine. I also ran jasmine tests in test/jasmine and test/jasmine.policy.tests.working. Everything seems to work.

**Comment by jplyle** [comment]
Thanks, Cesare!

**Comment by nix4** [comment]
I know this is already merged, but I'm finding a minor bug https://github.com/webinos/webinos-policy/blob/master/lib/policymanager.js#L72. 'Path' is not defined. Perhaps it should be 'path'.

**Pull request merged**
